/* Веб-шим @expo/vector-icons: Ionicons через react-icons/io5 (те же глифы Ionicons 5). */
import React from 'react';
import type { IconType } from 'react-icons';
import {
  IoAirplane,
  IoAlbums,
  IoAlertCircle,
  IoBagHandle,
  IoBarbell,
  IoBook,
  IoBriefcase,
  IoBus,
  IoBusiness,
  IoBusinessOutline,
  IoCafe,
  IoCalendarOutline,
  IoCard,
  IoCarSport,
  IoCart,
  IoCash,
  IoCheckmarkCircle,
  IoChevronBack,
  IoChevronDown,
  IoChevronForward,
  IoClose,
  IoCloseCircle,
  IoConstruct,
  IoCut,
  IoFilm,
  IoFitness,
  IoFlash,
  IoGameController,
  IoGift,
  IoGrid,
  IoHeart,
  IoHelpCircleOutline,
  IoHome,
  IoInformationCircle,
  IoMedkit,
  IoMusicalNotes,
  IoPaw,
  IoPeople,
  IoPerson,
  IoPersonCircle,
  IoPersonCircleOutline,
  IoPhonePortrait,
  IoPieChart,
  IoPieChartOutline,
  IoRepeat,
  IoRestaurant,
  IoRocket,
  IoSchool,
  IoSettingsOutline,
  IoShirt,
  IoSparkles,
  IoStar,
  IoTimeOutline,
  IoTrash,
  IoTrophy,
  IoTrophyOutline,
  IoTv,
  IoWallet,
  IoWalletOutline,
  IoWater,
  IoWifi,
} from 'react-icons/io5';

const glyphMap: Record<string, IconType> = {
  airplane: IoAirplane,
  albums: IoAlbums,
  'alert-circle': IoAlertCircle,
  'bag-handle': IoBagHandle,
  barbell: IoBarbell,
  book: IoBook,
  briefcase: IoBriefcase,
  bus: IoBus,
  business: IoBusiness,
  'business-outline': IoBusinessOutline,
  cafe: IoCafe,
  'calendar-outline': IoCalendarOutline,
  card: IoCard,
  'car-sport': IoCarSport,
  cart: IoCart,
  cash: IoCash,
  'checkmark-circle': IoCheckmarkCircle,
  'chevron-back': IoChevronBack,
  'chevron-down': IoChevronDown,
  'chevron-forward': IoChevronForward,
  close: IoClose,
  'close-circle': IoCloseCircle,
  construct: IoConstruct,
  cut: IoCut,
  film: IoFilm,
  fitness: IoFitness,
  flash: IoFlash,
  'game-controller': IoGameController,
  gift: IoGift,
  grid: IoGrid,
  heart: IoHeart,
  home: IoHome,
  'information-circle': IoInformationCircle,
  medkit: IoMedkit,
  'musical-notes': IoMusicalNotes,
  paw: IoPaw,
  people: IoPeople,
  person: IoPerson,
  'person-circle': IoPersonCircle,
  'person-circle-outline': IoPersonCircleOutline,
  'phone-portrait': IoPhonePortrait,
  'pie-chart': IoPieChart,
  'pie-chart-outline': IoPieChartOutline,
  repeat: IoRepeat,
  restaurant: IoRestaurant,
  rocket: IoRocket,
  school: IoSchool,
  'settings-outline': IoSettingsOutline,
  shirt: IoShirt,
  sparkles: IoSparkles,
  star: IoStar,
  'time-outline': IoTimeOutline,
  trash: IoTrash,
  trophy: IoTrophy,
  'trophy-outline': IoTrophyOutline,
  tv: IoTv,
  wallet: IoWallet,
  'wallet-outline': IoWalletOutline,
  water: IoWater,
  wifi: IoWifi,
};

type IoniconsProps = {
  name: string;
  size?: number;
  color?: string;
  style?: any;
};

function IoniconsComponent({ name, size = 24, color = 'currentColor', style }: IoniconsProps) {
  const Icon = glyphMap[name];
  if (!Icon) {
    if (import.meta.env.DEV) console.warn(`[vector-icons shim] неизвестная иконка: ${name}`);
    return <IoHelpCircleOutline size={size} color={color} style={{ flexShrink: 0, ...style }} />;
  }
  return <Icon size={size} color={color} style={{ flexShrink: 0, ...style }} />;
}

export const Ionicons = Object.assign(IoniconsComponent, { glyphMap });
